### PR TITLE
WIP: Scotland

### LINKED ISSUE #22: Add details stats on scotland
https://www.gov.scot/coronavirus-covid-19/

### LINKED ISSUE #53: PHE have pulled their CSVs
So right now the bot is failing to update them...

### PR DESCRIPTION
**Pull request by bertiebaggio**
Addresses #22 

**Adds**: Scotland; plus Wales, England, Northern Ireland to United Kingdom 'areas' in `data` structure.
**Adds**: Scottish regions (12) to United Kingdom 'areas' in `data` structure.

This uses data from [tomwhite/covid-19-uk-data](https://github.com/tomwhite/covid-19-uk-data). That repo does the work of scraping and updating data!

As that repo notes, the UK constituent countries update their data once per day; this is noted in `last_update` which uses the CSV's date + that country's stated update time. This is hopefully more accurate than timestamping with acquisition time, which could be misleading if done right before a scheduled update. That said, sometimes the updates are late.

### CODE REVIEW

**Comment by bertiebaggio** [comment]
## Examples

scottishfeature1

**Review by pwr22 — COMMENTED** [review]
Looking good so far!

**Comment by bertiebaggio** [comment]
Thanks. I think I uncovered a bug with my `!tables` implementation (now `!compare`, tho I haven't pulled from upstream yet); but my homeserver is offline so I've lost access to testing for now. I plan to return to this tomorrow after that's sorted.

**Comment by pwr22** [comment]
Hi @bertiebaggio sorry I haven't got back to you on this for a while! How's your homeserver doing now?

**Comment by bertiebaggio** [comment]
No worries, I've been involved with other things meantime!

I'm back up and running, I think; having some issues with maubot manager but I should be able to resolve that. I'll get this into a fit state to merge.

**Comment by pwr22** [comment]
You may want to hold off on resolving any conflicts for a bit because I'm in the middle of a big refactor and I'm being bad doing it directly on master :sob:.

**Comment by pwr22** [comment]
Ok, you should be good to go now :+1:.

**Review by pwr22 — APPROVED** [review]
Looks good to me :+1:. Is it ready to merge?

**Comment by bertiebaggio** [comment]
> Looks good to me . Is it ready to merge?

Thanks :)

I see per #53, PHE pulled their CSVs. That data is available through another [dashboard](https://coronavirus.data.gov.uk/) now; and gets pulled into Tom White's repo. As such it's (hopefully) trivial to integrate here. Worth doing in my opinion but a significant increase in terms of this PR's scope, so wanted to at least mention it before doing so it can be discussed.

**Comment by bertiebaggio** [comment]
After writing up the proposed expansion I checked to see what would be involved, and it took less time and characters to expand to UK than it did to write the previous comment :)

I have tidied up functions/variables to refer to UK regions as opposed to Scotland.

As such, this:

- fixes #22 
- fixes #53 

Cheers!

**Pull request merged**
